[build-system]
requires = ["setuptools>=64.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["transferring_transferability"]

[project]
name = "transferring_transferability"
version = "0.1.0"
license = { text = "MIT" }
dependencies = []